//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS_Common.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMS_Common.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DL trả kết quả sai.
        /// </summary>
        public static string DBErrDevMsg {
            get {
                return ResourceManager.GetString("DBErrDevMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra! Vui lòng liên hệ MISA.
        /// </summary>
        public static string DefaultUserMsg {
            get {
                return ResourceManager.GetString("DefaultUserMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản ghi cần xóa không tồn tại trong hệ thống.
        /// </summary>
        public static string DeleteNotExist {
            get {
                return ResourceManager.GetString("DeleteNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên đã tồn tại trong hệ thống!.
        /// </summary>
        public static string DuplicateEmployeeCode {
            get {
                return ResourceManager.GetString("DuplicateEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập đầy đủ các trường bắt buộc.
        /// </summary>
        public static string ErrorrRequiredValueEmptyUserMsg {
            get {
                return ResourceManager.GetString("ErrorrRequiredValueEmptyUserMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xảy ra exception.
        /// </summary>
        public static string ExceptionDevMsg {
            get {
                return ResourceManager.GetString("ExceptionDevMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban không hợp lệ. Vui lòng chọn lại.
        /// </summary>
        public static string InvalidDepartment {
            get {
                return ResourceManager.GetString("InvalidDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không dài quá 255 ký tự.
        /// </summary>
        public static string OutLengthAddress {
            get {
                return ResourceManager.GetString("OutLengthAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản không dài quá 50 ký tự.
        /// </summary>
        public static string OutLengthBankAccount {
            get {
                return ResourceManager.GetString("OutLengthBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi nhánh TK ngân hàng không dài quá 255 ký tự.
        /// </summary>
        public static string OutLengthBankBranchName {
            get {
                return ResourceManager.GetString("OutLengthBankBranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên ngân hàng không dài quá 255 ký tự.
        /// </summary>
        public static string OutLengthBankName {
            get {
                return ResourceManager.GetString("OutLengthBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không dài quá 50 ký tự.
        /// </summary>
        public static string OutLengthEmail {
            get {
                return ResourceManager.GetString("OutLengthEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường này không dài quá 20 ký tự.
        /// </summary>
        public static string OutLengthEmployeeCode {
            get {
                return ResourceManager.GetString("OutLengthEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân viên không dài quá 100 ký tự.
        /// </summary>
        public static string OutLengthEmployeeName {
            get {
                return ResourceManager.GetString("OutLengthEmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi cấp không dài quá 255 ký tự.
        /// </summary>
        public static string OutLengthIdentityIssuePlace {
            get {
                return ResourceManager.GetString("OutLengthIdentityIssuePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số chứng minh nhân dân không dài quá 50 ký tự.
        /// </summary>
        public static string OutLengthIdentityNumber {
            get {
                return ResourceManager.GetString("OutLengthIdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại cố định không dài quá 50 ký tự.
        /// </summary>
        public static string OutLengthPhoneNumber {
            get {
                return ResourceManager.GetString("OutLengthPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại di động không dài quá 50 ký tự.
        /// </summary>
        public static string OutLengthTelephoneNumber {
            get {
                return ResourceManager.GetString("OutLengthTelephoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản ghi cần sửa không tồn tại trong hệ thống.
        /// </summary>
        public static string UpdateNotExist {
            get {
                return ResourceManager.GetString("UpdateNotExist", resourceCulture);
            }
        }
    }
}
